pipeline{
    agent any
    stages{
        stage("SCM Checkout"){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout', deleteUntrackedNestedRepositories: true]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github-login', url: 'https://github.com/Prospica/demo-pipeline']]])
            }
        }
        stage("Create Image"){
            steps{
                sh '''
                docker build -t prospica/demo-pipeline:v1 .
                '''
            }
        }
        stage("Push Image"){
            steps{
                sh '''
                set +x
                docker login --username=prospica --password=$dockerPassword
                set -x
                docker push prospica/demo-pipeline:v1
                '''
            }
        }
    }
}
